apiVersion: v1
kind: Service
metadata:
  name: mynats
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: nats-server
  ports:
    - name: nats
      port: 4222
    - name: cluster
      port: 6222
    - name: monitor
      port: 8222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nats-server
  template:
    metadata:
      labels:
        app: nats-server
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: nats-server
      containers:
        - name: nats-server
          image: nats
          imagePullPolicy: Always
          command: [ "nats-server" ]
          args: [ "--cluster_name", "mynats", "--cluster", "nats://0.0.0.0:6222", "--routes", "nats://mynats.sandbox:6222", "-m", "8222" ]
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
          ports:
            - containerPort: 4222
            - containerPort: 6222
            - containerPort: 8222
