apiVersion: v1
kind: Service
metadata:
  name: mongo-server
spec:
  selector:
    app: mongo-server
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-server
  template:
    metadata:
      labels:
        app: mongo-server
    spec:
      containers:
        - name: mongo-server
          image: srvu:5000/mongo-server:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
