apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
    - name: http
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: Recreate # "Another mongod instance is already running on the /data/db directory"
  template:
    metadata:
      labels:
        app: mongo
    spec:
      nodeSelector:
        kubernetes.io/hostname: gergo
      containers:
        - name: mongodb
          image: mongo
          env:
            - name: "MONGO_INITDB_ROOT_USERNAME"
              value: "root"
            - name: "MONGO_INITDB_ROOT_PASSWORD"
              value: "TODO"
          volumeMounts:
            - name: data-vol
              mountPath: /data/db
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        - name: mongo-express
          image: mongo-express
          env:
            - name: "ME_CONFIG_MONGODB_ADMINUSERNAME"
              value: "root"
            - name: "ME_CONFIG_MONGODB_ADMINPASSWORD"
              value: "TODO"
            - name: "ME_CONFIG_MONGODB_URL"
              value: "mongodb://root:TODO@127.0.0.1:27017/admin"
          resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
      volumes:
        - name: data-vol
          hostPath:
            path: /tmp/mongo
            type: DirectoryOrCreate
